name: 'Get Branch and Pull'
description: 'Find Branch name in comment then pull that Branch'
inputs:
  run-arguments:  # issue comment
    description: 'Issue comment'
    required: true
runs:
  using: "composite"
  steps:


    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        ref: 1
