name: CD

# SECRETS needed:
### FIREBASE_TOKEN
### SSH_PRIVATE_KEY for Match Repo
### MATCH_PASS

on:
  push:
    branches: [ master ]
    paths: 
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:

  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run SwiftLint
      uses: norio-nomura/action-swiftlint@3.1.0
      with:
        args: --strict 
        
    - name: Comment on failure
      if: ${{ failure() }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
            There was a linting error (warning / error) in this PR.
            Please check the errors from CI log at https://github.com/dee-money/passenger-ios/actions
        
  Build:
    name: Build
    runs-on: macOS-latest

    steps:
    - name: Cancel Previous Runs

      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    # - name: Select Xcode

    #   run: sudo xcode-select -switch /Applications/Xcode_12.4.app && /usr/bin/xcodebuild -version

    - uses: actions/checkout@v2
    # Set fetch-depth (default: 1) to get whole tree
      with:
        fetch-depth: 0

    - name: Install SSH key

      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Firebase-Tools

      run: |
        yarn global add firebase-tools
        echo "$(yarn global bin)" >> $GITHUB_PATH
            
    - name: Bundle install
      # if: steps.bundleCache.outputs.cache-hit != 'true'
      run: |
        bundle install

    - name: match Ad-hoc
      run: |
        bundle exec fastlane run setup_ci
        bundle exec fastlane syncSigningCI
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}

    - uses: actions/cache@v2
      id: cocoapodCache
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Install Pods Dependencies
      run: |
        bundle exec pod install
      shell: bash

    # - name: Test App

    #   run: bundle exec fastlane test

    - name: Build and Test
      run: xcodebuild -workspace GithubActionDemo.xcworkspace -scheme 'GithubActionDemo Staging' -destination 'platform=iOS Simulator,name=iPhone 12' clean test | xcpretty

    - name: Build App and Distibute to Firebase
      run: bundle exec fastlane build_and_upload_staging_app
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}