name: check_phraseapp

# SECRETS needed:
### PHRASEAPP_TOKEN

on:

  push:
    branches: [ master ]

jobs:

  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Bundle install
          run: |
            bundle install
          
    - name: Check PhraseApp
          run: |
            bundle exec ruby Scripts/phraseapp_check.rb