name: check_phraseapp

# SECRETS needed:
### PHRASEAPP_TOKEN

on:

  push:
    branches: [ develop, master ]

jobs:

  Lint:
    name: Check PhraseApp
    runs-on: ubuntu-latest
    steps:

    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Bundle install
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

          
    - name: Check PhraseApp
      run: |
        bundle exec ruby Scripts/phraseapp_check.rb
      env:
        PHRASEAPP_TOKEN: ${{ secrets.PHRASEAPP_TOKEN }}