# This is a basic workflow to help you get started with Actions

name: CIer

on:
  issue_comment:
    types: [created]
    paths: 
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  Lint:
    name: Lint
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/CI_test')
    runs-on: ubuntu-latest
    steps:
    
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}
    - name: Environment
      run: env | sort
      
    - name: Checkout code
      uses: actions/checkout@v2
        
