name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2


    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: install firebase tool
      run: |
        yarn global add firebase-tools
        echo "::add-path::$(yarn global bin)"
    - name: setup fastlane
      run: bundle install
    - name: match adhoc
      run: bundle exec fastlane syncAdhocSigningCI
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}

    - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Install Dependencies
      run: |
        pod install --repo-update
      shell: bash


    - name: Install Fastlane Firebase Distribution
      run: fastlane add_plugin firebase_app_distribution
      
    - name: Build App
      run: bundle exec fastlane build_and_upload_staging_app
