name: Swift

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: skip or not
        id: skipornot
        with:
          token: ${{ secrets.personalAccessToken }}
        uses: atlwendy/retrieve-commit-messages-from-pr@v3
      - name: get my action output
        run: echo ::set-env name=SHOULD_RUN::${{ steps.skipornot.outputs.shouldRun }}
      - name: build
        run: yarn run build
        if: env.SHOULD_RUN == 'true'
